### ISSUE TITLE
bug: panic on trying to inspect different route in devtools

### ISSUE THREAD

**Issue by ugniussle** [marc2332/freya#1246]
Trying to inspect a route's other than the main one's elements results in a panic:
```
thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/dioxus-router-0.6.3/src/contexts/router.rs:243:17:
route's display implementation must be parsable by FromStr
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Minimal reproduction:
main.rs
```rust
use freya::prelude::*;
use dioxus_router::prelude::{Routable, Outlet, Router};

fn main() {
    launch(App);
}

#[derive(Debug, Clone, Routable, PartialEq)]
#[rustfmt::skip]
enum Route {
    #[layout(Navbar)]
        #[route("/")]
        View1 {},

        #[route("/view2")]
        View2 {},
}

#[component]
fn App() -> Element {
    rsx! {
        Body {
            Router::<Route> {}
        }
    }
}

#[component]
pub fn Navbar() -> Element {
    rsx! {
        rect {
            height: "24",
            width: "100%",
            direction: "horizontal",
            spacing: "6",
            Link {
                to: Route::View1 {},
                label { "View1" }
            },
            Link {
                to: Route::View2 {},
                label { "View2" }
            },
        }

        Outlet::<Route> {}
    }
}

#[component]
fn View1() -> Element {
    rsx!{
        rect {
            label {"hello"}
        }
    }
}

#[component]
fn View2() -> Element {
    rsx!{
        rect {
            label {"hello2"}
        }
    }
}
```

Cargo.toml
```toml
[package]
name = "reproduce_route_bug"
version = "0.1.0"
edition = "2024"

[dependencies]
freya = { version="0.3.4", features = ["devtools"] }
dioxus-router = { version = "0.6.3", default-features = false }

```
