### ISSUE TITLE
docs: Add a mention that custom linkers are not officially supported yet

### ISSUE THREAD

**Issue by marc2332** [marc2332/freya#582]
Some people might have unexpected behaviors (like segmentation faults!) when developing freya apps with a custom linker such as `mold`. There should be a mention of this in the docs.

**Comment by Andrew15-5** [comment]
Don't put this in you're cargo `config.toml`, kids! (not yet!)

```toml
[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-fuse-ld=mold",
]
```
